Traceback (most recent call last):
  File "/home/runner/PrimeClaims/.pythonlibs/lib/python3.11/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/home/runner/PrimeClaims/.pythonlibs/lib/python3.11/site-packages/gunicorn/arbiter.py", line 360, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/PrimeClaims/.pythonlibs/lib/python3.11/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/runner/PrimeClaims/.pythonlibs/lib/python3.11/site-packages/gunicorn/arbiter.py", line 530, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/PrimeClaims/.pythonlibs/bin/gunicorn", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/runner/PrimeClaims/.pythonlibs/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/runner/PrimeClaims/.pythonlibs/lib/python3.11/site-packages/gunicorn/app/base.py", line 236, in run
    super().run()
  File "/home/runner/PrimeClaims/.pythonlibs/lib/python3.11/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/runner/PrimeClaims/.pythonlibs/lib/python3.11/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/runner/PrimeClaims/.pythonlibs/lib/python3.11/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/home/runner/PrimeClaims/.pythonlibs/lib/python3.11/site-packages/gunicorn/arbiter.py", line 396, in stop
    time.sleep(0.1)
  File "/home/runner/PrimeClaims/.pythonlibs/lib/python3.11/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/runner/PrimeClaims/.pythonlibs/lib/python3.11/site-packages/gunicorn/arbiter.py", line 530, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)